version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration-service:
    build:
      context: Ecommerce.MigrationService
      dockerfile: Dockerfile
    container_name: ecommerce-migration
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings_DefaultConnection: "Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    depends_on:
      - postgres
    restart: on-failure
    tty: true

volumes:
  pgdata:
