version: "3.9"

services:
  # ecommerce-db:
  #   image: postgres:16
  #   container_name: ecommerce-db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  migration-service:
    build:
      context: .
      dockerfile: Ecommerce.MigrationService/Dockerfile
    container_name: ecommerce-migration
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
    # depends_on:
      # - ecommerce-db
    restart: on-failure
    tty: true

  # ecommerce-apphost:
  #   build:
  #     context: .
  #     dockerfile: Ecommerce/Ecommerce.AppHost/Dockerfile
  #   container_name: ecommerce-apphost
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ConnectionStrings__DefaultConnection: "Host=ecommerce-db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
  #      ConnectionStrings__DefaultConnection: "${POSTGRES_URL}"
  #   ports:
  #     - "5000:8080"
  #   depends_on:
  #     - ecommerce-db
  #     - migration-service
  ecommerce-api:
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile
    container_name: ecommerce-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      # VNPay Configuration
      VnPay__TmnCode: ${VNPAY_TMN_CODE}
      VnPay__HashSecret: ${VNPAY_HASH_SECRET}
      VnPay__BaseUrl: ${VNPAY_BASE_URL}
      VnPay__Version: ${VNPAY_VERSION}
      VnPay__Command: ${VNPAY_COMMAND}
      VnPay__CurrCode: ${VNPAY_CURR_CODE}
      VnPay__Locale: ${VNPAY_LOCALE}
      VnPay__ReturnUrl: ${VNPAY_RETURN_URL}
      TimeZoneId: ${TIMEZONE_ID}
      # config JWT
      JWT__KEY: ${JWT__KEY}
      JWT__ISSUER: ${JWT__ISSUER}
      JWT__AUDIENCE: ${JWT__AUDIENCE}
      JWT__EXPIRYINMINUTES: ${JWT__EXPIRYINMINUTES}
      JWT__REFRESHTOKENEXPIRYINDAYS: ${JWT__REFRESHTOKENEXPIRYINDAYS}
      #cloud img
      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME}
      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY}
      Cloudinary__ApiSecret: ${CLOUDINARY_API_SECRET}
    ports:
      - "5000:8080" # Cho phép FE gọi http://localhost:5000
    depends_on:
      # - ecommerce-db
      - migration-service
    volumes:
      - ./Ecommerce.API/wwwroot/images:/app/wwwroot/images


# volumes:
#   pgdata: